EfCore1/Areas/Admin/Controllers/OurModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFCore.DataAccess.Data;
using EFCore.Models.Models;

namespace EfCore1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OurModelsController : Controller
    {
        private readonly AppDbContext _context;

        public OurModelsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: OurModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.OurMM.ToListAsync());

        }

        // GET: OurModels/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourModel = await _context.OurMM
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ourModel == null)
            {
                return NotFound();
            }

            return View(ourModel);
        }

        // GET: OurModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: OurModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,AuthorName")] OurModel ourModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ourModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ourModel);
        }

        // GET: OurModels/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourModel = await _context.OurMM.FindAsync(id);
            if (ourModel == null)
            {
                return NotFound();
            }
            return View(ourModel);
        }

        // POST: OurModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,AuthorName")] OurModel ourModel)
        {
            if (id != ourModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ourModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OurModelExists(ourModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ourModel);
        }

        // GET: OurModels/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourModel = await _context.OurMM
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ourModel == null)
            {
                return NotFound();
            }

            return View(ourModel);
        }

        // POST: OurModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var ourModel = await _context.OurMM.FindAsync(id);
            if (ourModel != null)
            {
                _context.OurMM.Remove(ourModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OurModelExists(string id)
        {
            return _context.OurMM.Any(e => e.Id == id);
        }
    }
}

EfCore1/Controllers/MelissaModelsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EFCore.Models;
using EFCore.DataAccess.Data;


namespace EfCore1.Controllers
{
    public class MelissaModelsController : Controller
    {
        private readonly AppDbContext _context;

        public MelissaModelsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: MelissaModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.MmModel.ToListAsync());
        }

        // GET: MelissaModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var melissaModel = await _context.MmModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (melissaModel == null)
            {
                return NotFound();
            }

            return View(melissaModel);
        }

        // GET: MelissaModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MelissaModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,College,Age")] MelissaModel melissaModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(melissaModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(melissaModel);
        }

        // GET: MelissaModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var melissaModel = await _context.MmModel.FindAsync(id);
            if (melissaModel == null)
            {
                return NotFound();
            }
            return View(melissaModel);
        }

        // POST: MelissaModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,College,Age")] MelissaModel melissaModel)
        {
            if (id != melissaModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(melissaModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MelissaModelExists(melissaModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(melissaModel);
        }

        // GET: MelissaModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var melissaModel = await _context.MmModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (melissaModel == null)
            {
                return NotFound();
            }

            return View(melissaModel);
        }

        // POST: MelissaModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var melissaModel = await _context.MmModel.FindAsync(id);
            if (melissaModel != null)
            {
                _context.MmModel.Remove(melissaModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MelissaModelExists(int id)
        {
            return _context.MmModel.Any(e => e.Id == id);
        }
    }
}

EfCore1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfCore1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EfCore1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EfCore1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-success" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Privacy"><b>Privacy</b></a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-danger" asp-area="SecendArea" asp-controller="MelissaModels" asp-action="Index"><b>DATA</b></a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-danger" asp-area="Admin" asp-controller="OurModels" asp-action="Create"><b>Creating data on OurModels</b></a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EfCore1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>